USE [master]
GO

/****** Object:  Database [crudmvc]    Script Date: 05/01/2023 08:20:31 p. m. ******/
DROP DATABASE [crudmvc]
GO

/****** Object:  Database [crudmvc]    Script Date: 05/01/2023 08:20:31 p. m. ******/
CREATE DATABASE [crudmvc]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'crudmvc', FILENAME = N'D:\Program Files\Microsft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\crudmvc.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'crudmvc_log', FILENAME = N'D:\Program Files\Microsft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\crudmvc_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [crudmvc].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [crudmvc] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [crudmvc] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [crudmvc] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [crudmvc] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [crudmvc] SET ARITHABORT OFF 
GO

ALTER DATABASE [crudmvc] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [crudmvc] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [crudmvc] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [crudmvc] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [crudmvc] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [crudmvc] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [crudmvc] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [crudmvc] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [crudmvc] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [crudmvc] SET  ENABLE_BROKER 
GO

ALTER DATABASE [crudmvc] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [crudmvc] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [crudmvc] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [crudmvc] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [crudmvc] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [crudmvc] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [crudmvc] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [crudmvc] SET RECOVERY FULL 
GO

ALTER DATABASE [crudmvc] SET  MULTI_USER 
GO

ALTER DATABASE [crudmvc] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [crudmvc] SET DB_CHAINING OFF 
GO

ALTER DATABASE [crudmvc] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [crudmvc] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [crudmvc] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [crudmvc] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [crudmvc] SET QUERY_STORE = OFF
GO

ALTER DATABASE [crudmvc] SET  READ_WRITE 
GO

